// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvWGT8vCR2DcCo9V2QocklPehH07GcF5E',
    appId: '1:306474016365:web:87089abe3c1b8c26d46964',
    messagingSenderId: '306474016365',
    projectId: 'edukesyenassignment',
    authDomain: 'edukesyenassignment.firebaseapp.com',
    storageBucket: 'edukesyenassignment.appspot.com',
    measurementId: 'G-WHVW629YD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBppNIiNCIK-I2KZqzUAZjltbaog-qj6s',
    appId: '1:306474016365:android:7d6378ee3d6089cfd46964',
    messagingSenderId: '306474016365',
    projectId: 'edukesyenassignment',
    storageBucket: 'edukesyenassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6oqgwBrbrmRCH9OaPrNNgLMKYv2LIwM',
    appId: '1:306474016365:ios:a18f9584bbe4f72ad46964',
    messagingSenderId: '306474016365',
    projectId: 'edukesyenassignment',
    storageBucket: 'edukesyenassignment.appspot.com',
    iosBundleId: 'com.example.edukesyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK6oqgwBrbrmRCH9OaPrNNgLMKYv2LIwM',
    appId: '1:306474016365:ios:a18f9584bbe4f72ad46964',
    messagingSenderId: '306474016365',
    projectId: 'edukesyenassignment',
    storageBucket: 'edukesyenassignment.appspot.com',
    iosBundleId: 'com.example.edukesyen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvWGT8vCR2DcCo9V2QocklPehH07GcF5E',
    appId: '1:306474016365:web:0d0a2ad029e8b903d46964',
    messagingSenderId: '306474016365',
    projectId: 'edukesyenassignment',
    authDomain: 'edukesyenassignment.firebaseapp.com',
    storageBucket: 'edukesyenassignment.appspot.com',
    measurementId: 'G-Q3M1MSMGL1',
  );
}
